name: ar_flutter_plugin_engine
description: Flutter Plugin for AR experiences (ARKit & ARCore)
version: 1.0.1
homepage: https://github.com/dherediat97
repository: https://github.com/dherediat97/ar_flutter_plugin_engine

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  vector_math: ^2.2.0
  json_annotation: ^4.9.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dherediat97.ar_flutter_plugin_engine
        pluginClass: ArFlutterPluginEngine
      ios:
        pluginClass: ArFlutterPlugin
